const list = [
  {
    name: "Afghanistan",
    topLevelDomain: [".af"],
    alpha2Code: "AF",
    alpha3Code: "AFG",
    callingCodes: ["93"],
    capital: "Kabul",
    altSpellings: ["AF", "AfÄ¡Ä\u0081nistÄ\u0081n"],
    subregion: "Southern Asia",
    region: "Asia",
    population: 40218234,
    latlng: [33, 65],
    demonym: "Afghan",
    area: 652230,
    timezones: ["UTC+04:30"],
    borders: ["IRN", "PAK", "TKM", "UZB", "TJK", "CHN"],
    nativeName: "Ø§Ù\u0081ØºØ§Ù†Ø³ØªØ§Ù†",
    numericCode: "004",
    flags: {
      svg: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
      png: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
    },
    currencies: [
      {
        code: "AFN",
        name: "Afghan afghani",
        symbol: "Ø‹",
      },
    ],
    languages: [
      {
        iso639_1: "ps",
        iso639_2: "pus",
        name: "Pashto",
        nativeName: "Ù¾ÚšØªÙˆ",
      },
      {
        iso639_1: "uz",
        iso639_2: "uzb",
        name: "Uzbek",
        nativeName: "OÊ»zbek",
      },
      {
        iso639_1: "tk",
        iso639_2: "tuk",
        name: "Turkmen",
        nativeName: "TÃ¼rkmen",
      },
    ],
    translations: {
      br: "AfeganistÃ£o",
      pt: "AfeganistÃ£o",
      nl: "Afghanistan",
      hr: "Afganistan",
      fa: "Ø§Ù\u0081ØºØ§Ù†Ø³ØªØ§Ù†",
      de: "Afghanistan",
      es: "AfganistÃ¡n",
      fr: "Afghanistan",
      ja: "ã‚¢ãƒ•ã‚¬ãƒ‹ã‚¹ã‚¿ãƒ³",
      it: "Afghanistan",
      hu: "AfganisztÃ¡n",
    },
    flag: "https://upload.wikimedia.org/wikipedia/commons/5/5c/Flag_of_the_Taliban.svg",
    regionalBlocs: [
      {
        acronym: "SAARC",
        name: "South Asian Association for Regional Cooperation",
      },
    ],
    cioc: "AFG",
    independent: true,
  },
  {
    name: "Ã…land Islands",
    topLevelDomain: [".ax"],
    alpha2Code: "AX",
    alpha3Code: "ALA",
    callingCodes: ["358"],
    capital: "Mariehamn",
    altSpellings: ["AX", "Aaland", "Aland", "Ahvenanmaa"],
    subregion: "Northern Europe",
    region: "Europe",
    population: 28875,
    latlng: [60.116667, 19.9],
    demonym: "Ã…landish",
    area: 1580,
    timezones: ["UTC+02:00"],
    nativeName: "Ã…land",
    numericCode: "248",
    flags: {
      svg: "https://flagcdn.com/ax.svg",
      png: "https://flagcdn.com/w320/ax.png",
    },
    currencies: [
      {
        code: "EUR",
        name: "Euro",
        symbol: "â‚¬",
      },
    ],
    languages: [
      {
        iso639_1: "sv",
        iso639_2: "swe",
        name: "Swedish",
        nativeName: "svenska",
      },
    ],
    translations: {
      br: "Ilhas de Aland",
      pt: "Ilhas de Aland",
      nl: "Ã…landeilanden",
      hr: "Ã…landski otoci",
      fa: "Ø¬Ø²Ø§ÛŒØ± Ø§Ù„Ù†Ø¯",
      de: "Ã…land",
      es: "Alandia",
      fr: "Ã…land",
      ja: "ã‚ªãƒ¼ãƒ©ãƒ³ãƒ‰è«¸å³¶",
      it: "Isole Aland",
      hu: "Ã…land-szigetek",
    },
    flag: "https://flagcdn.com/ax.svg",
    regionalBlocs: [
      {
        acronym: "EU",
        name: "European Union",
      },
    ],
    independent: false,
  },
  {
    name: "Albania",
    topLevelDomain: [".al"],
    alpha2Code: "AL",
    alpha3Code: "ALB",
    callingCodes: ["355"],
    capital: "Tirana",
    altSpellings: ["AL", "ShqipÃ«ri", "ShqipÃ«ria", "Shqipnia"],
    subregion: "Southern Europe",
    region: "Europe",
    population: 2837743,
    latlng: [41, 20],
    demonym: "Albanian",
    area: 28748,
    gini: 33.2,
    timezones: ["UTC+01:00"],
    borders: ["MNE", "GRC", "MKD", "UNK"],
    nativeName: "ShqipÃ«ria",
    numericCode: "008",
    flags: {
      svg: "https://flagcdn.com/al.svg",
      png: "https://flagcdn.com/w320/al.png",
    },
    currencies: [
      {
        code: "ALL",
        name: "Albanian lek",
        symbol: "L",
      },
    ],
    languages: [
      {
        iso639_1: "sq",
        iso639_2: "sqi",
        name: "Albanian",
        nativeName: "Shqip",
      },
    ],
    translations: {
      br: "AlbÃ¢nia",
      pt: "AlbÃ¢nia",
      nl: "AlbaniÃ«",
      hr: "Albanija",
      fa: "Ø¢Ù„Ø¨Ø§Ù†ÛŒ",
      de: "Albanien",
      es: "Albania",
      fr: "Albanie",
      ja: "ã‚¢ãƒ«ãƒ\u0090ãƒ‹ã‚¢",
      it: "Albania",
      hu: "AlbÃ¡nia",
    },
    flag: "https://flagcdn.com/al.svg",
    regionalBlocs: [
      {
        acronym: "CEFTA",
        name: "Central European Free Trade Agreement",
      },
    ],
    cioc: "ALB",
    independent: true,
  },
  {
    name: "Algeria",
    topLevelDomain: [".dz"],
    alpha2Code: "DZ",
    alpha3Code: "DZA",
    callingCodes: ["213"],
    capital: "Algiers",
    altSpellings: ["DZ", "Dzayer", "AlgÃ©rie"],
    subregion: "Northern Africa",
    region: "Africa",
    population: 44700000,
    latlng: [28, 3],
    demonym: "Algerian",
    area: 2381741,
    gini: 27.6,
    timezones: ["UTC+01:00"],
    borders: ["TUN", "LBY", "NER", "ESH", "MRT", "MLI", "MAR"],
    nativeName: "Ø§Ù„Ø¬Ø²Ø§Ø¦Ø±",
    numericCode: "012",
    flags: {
      svg: "https://flagcdn.com/dz.svg",
      png: "https://flagcdn.com/w320/dz.png",
    },
    currencies: [
      {
        code: "DZD",
        name: "Algerian dinar",
        symbol: "Ø¯.Ø¬",
      },
    ],
    languages: [
      {
        iso639_1: "ar",
        iso639_2: "ara",
        name: "Arabic",
        nativeName: "Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©",
      },
    ],
    translations: {
      br: "ArgÃ©lia",
      pt: "ArgÃ©lia",
      nl: "Algerije",
      hr: "AlÅ¾ir",
      fa: "Ø§Ù„Ø¬Ø²Ø§ÛŒØ±",
      de: "Algerien",
      es: "Argelia",
      fr: "AlgÃ©rie",
      ja: "ã‚¢ãƒ«ã‚¸ã‚§ãƒªã‚¢",
      it: "Algeria",
      hu: "AlgÃ©ria",
    },
    flag: "https://flagcdn.com/dz.svg",
    regionalBlocs: [
      {
        acronym: "AU",
        name: "African Union",
        otherNames: [
          "Ø§Ù„Ø§ØªØ\u00adØ§Ø¯ Ø§Ù„Ø£Ù\u0081Ø±ÙŠÙ‚ÙŠ",
          "Union africaine",
          "UniÃ£o Africana",
          "UniÃ³n Africana",
          "Umoja wa Afrika",
        ],
      },
      {
        acronym: "AL",
        name: "Arab League",
        otherNames: [
          "Ø¬Ø§Ù…Ø¹Ø© Ø§Ù„Ø¯ÙˆÙ„ Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©",
          "JÄ\u0081miÊ»at ad-Duwal al-Ê»ArabÄ«yah",
          "League of Arab States",
        ],
      },
    ],
    cioc: "ALG",
    independent: true,
  },
];

export default list;
